// DHS Trusted Tester v5 test catalog.
// Source: https://section508coordinators.github.io/TrustedTester/appendixc.html
//
// automation:
//   auto    - determinate failures are detected automatically (plus escalations)
//   partial - some conditions detected; the rest is escalated for human review
//   manual  - cannot be automated; listed in the manual checklist of every report

export const CATALOG = {
  '1.A': { name: 'alt-version-conformant', wcag: 'Conformance Req.', automation: 'manual',
    condition: 'An alternate version passes all applicable Test Conditions in this test process.',
    note: 'Only applies if the site offers a separate "accessible version". Test that version with this tool as well.' },
  '1.B': { name: 'alt-version-equivalent', wcag: 'Conformance Req.', automation: 'manual',
    condition: 'The accessible version is up to date with the same information and functionality.' },
  '1.C': { name: 'alt-version-access', wcag: 'Conformance Req.', automation: 'manual',
    condition: 'The mechanism to reach the accessible equivalent version from the non-conforming page is accessible.' },
  '1.D': { name: 'alt-version-nc-access', wcag: 'Conformance Req.', automation: 'manual',
    condition: 'The non-conforming version(s) can only be reached from conforming content.' },
  '1.E': { name: 'non-interference', wcag: 'Conformance Req. 5', automation: 'manual',
    condition: 'Content in the non-conforming version(s) does not interfere with the user’s ability to access or use the conforming content.' },
  '2.A': { name: '1.4.2-audio-control', wcag: '1.4.2', automation: 'partial',
    condition: 'The user can pause, stop, or control the volume of audio content that plays automatically.' },
  '2.B': { name: '2.2.2-blinking-moving-scrolling', wcag: '2.2.2', automation: 'partial',
    condition: 'The user can pause, stop, or hide moving, blinking, or scrolling content.' },
  '2.C': { name: '2.2.2-auto-updating', wcag: '2.2.2', automation: 'partial',
    condition: 'The user can pause, stop, hide, or control the frequency of automatically updating content.' },
  '2.D': { name: '4.1.2-change-notify-auto', wcag: '4.1.2', automation: 'manual',
    condition: 'The page provides notification of each automatic update/change in content.',
    note: 'With a screen reader running, confirm automatic content changes are announced (aria-live or focus management).' },
  '3.A': { name: '2.3.1-flashing', wcag: '2.3.1', automation: 'partial',
    condition: 'If no flashing content is found this test does not apply. If flashing content is found, record as NOT TESTED.',
    note: 'Trusted Tester does not test flashing thresholds. Record any content that flashes more than 3 times per second.' },
  '4.A': { name: '2.1.1-keyboard-access', wcag: '2.1.1', automation: 'partial',
    condition: 'All functionality can be accessed and executed using only the keyboard.' },
  '4.B': { name: '2.1.1-no-keystroke-timing', wcag: '2.1.1', automation: 'manual',
    condition: 'Individual keystrokes do not require specific timings for activation of functionality.',
    note: 'Look for controls that require holding a key, double-pressing quickly, or typing within a time window.' },
  '4.C': { name: '2.1.2-no-keyboard-trap', wcag: '2.1.2', automation: 'auto',
    condition: 'There is no keyboard trap.' },
  '4.D': { name: '2.4.7-focus-visible', wcag: '2.4.7', automation: 'auto',
    condition: 'A visible indication of focus is provided when focus is on the interface component.' },
  '4.E': { name: '3.2.1-on-focus', wcag: '3.2.1', automation: 'partial',
    condition: 'When an interface component receives focus, it does not initiate an unexpected change of context.' },
  '4.F': { name: '2.4.3-focus-order-meaning', wcag: '2.4.3', automation: 'partial',
    condition: 'The focus order preserves the meaning and operability of the web page.' },
  '4.G': { name: '2.4.3-focus-order-reveal', wcag: '2.4.3', automation: 'partial',
    condition: 'Focus is moved to revealed content.' },
  '4.H': { name: '2.4.3-focus-order-return', wcag: '2.4.3', automation: 'partial',
    condition: 'Focus is returned to the logical sequence.' },
  '5.A': { name: '3.3.2-label-provided', wcag: '3.3.2', automation: 'auto',
    condition: 'Labels and instructions are provided for each form input.' },
  '5.B': { name: '2.4.6-label-descriptive', wcag: '2.4.6', automation: 'partial',
    condition: 'Each form label is sufficiently descriptive.' },
  '5.C': { name: '1.3.1-programmatic-label', wcag: '1.3.1 / 4.1.2', automation: 'partial',
    condition: 'The combination of the accessible name, accessible description, and other programmatic associations describes each input field and includes all relevant instructions and cues.' },
  '5.D': { name: '3.2.2-on-input', wcag: '3.2.2', automation: 'partial',
    condition: 'Changing field values/selections does not initiate an unexpected change of context.' },
  '5.E': { name: '4.1.2-change-notify-form', wcag: '4.1.2', automation: 'manual',
    condition: 'The page provides notification of each form-related change in content.',
    note: 'With a screen reader, confirm that content revealed or changed by form interaction is announced.' },
  '5.F': { name: '3.3.1-error-identification', wcag: '3.3.1', automation: 'partial',
    condition: 'The item in error is identified and the error is described to the user in text.' },
  '5.G': { name: '3.3.3-error-suggestion', wcag: '3.3.3', automation: 'manual',
    condition: 'Additional guidance (e.g., suggestion for corrected input) is provided about how to correct errors for form fields.',
    note: 'Submit each form with invalid data and confirm the error text says how to fix the input.' },
  '5.H': { name: '3.3.4-error-prevention', wcag: '3.3.4', automation: 'partial',
    condition: 'The web page allows the user to check, reverse, and/or confirm submission (legal, financial, or data-modifying transactions).' },
  '6.A': { name: '2.4.4-link-purpose', wcag: '2.4.4 / 4.1.2', automation: 'partial',
    condition: 'The purpose of each link or button can be determined from the text, accessible name, accessible description, and/or programmatically determined context.' },
  '6.B': { name: '4.1.2-change-notify-links', wcag: '4.1.2', automation: 'manual',
    condition: 'The page provides notification of each change in content that is the result of interaction with a link or button.',
    note: 'With a screen reader, activate links and buttons that change page content and confirm the change is announced.' },
  '7.A': { name: '1.1.1-meaningful-image-name', wcag: '1.1.1', automation: 'partial',
    condition: 'The accessible name and accessible description for a meaningful image provides an equivalent description of the image.' },
  '7.B': { name: '1.1.1-decorative-image', wcag: '1.1.1', automation: 'partial',
    condition: 'There is no accessible name and accessible description for a decorative image.' },
  '7.C': { name: '1.1.1-decorative-background-image', wcag: '1.1.1', automation: 'partial',
    condition: 'The background image is not the only means used to convey important information.' },
  '7.D': { name: '1.1.1-captcha-alternative', wcag: '1.1.1', automation: 'partial',
    condition: 'Alternative forms of CAPTCHA are provided.' },
  '7.E': { name: '1.4.5-image-of-text', wcag: '1.4.5', automation: 'manual',
    condition: 'The image of text cannot be replaced by text or is customizable.',
    note: 'Review the image inventory in each page’s 7.A escalation; any image whose content is text (other than logos) needs justification.' },
  '8.A': { name: '2.2.1-timing-adjustable', wcag: '2.2.1', automation: 'partial',
    condition: 'The user can turn off, adjust, or extend the time limit.' },
  '9.A': { name: '2.4.1-bypass-function', wcag: '2.4.1', automation: 'auto',
    condition: 'A keyboard-accessible method is provided to bypass repetitive content.' },
  '9.B': { name: '3.2.3-consistent-navigation', wcag: '3.2.3', automation: 'auto',
    condition: 'Each navigational element occurs in the same relative order with regard to other repeated components on each web page where it appears.' },
  '9.C': { name: '3.2.4-consistent-identification', wcag: '3.2.4', automation: 'partial',
    condition: 'The accessible name and description is consistent for components that perform the same function.' },
  '10.A': { name: '2.4.6-heading-purpose', wcag: '2.4.6', automation: 'manual',
    condition: 'Each heading describes the topic or purpose of its content.',
    note: 'Each page report lists its heading outline for review.' },
  '10.B': { name: '1.3.1-heading-determinable', wcag: '1.3.1', automation: 'partial',
    condition: 'Each programmatically determinable heading is a visual heading and each visual heading is programmatically determinable.' },
  '10.C': { name: '1.3.1-heading-level', wcag: '1.3.1', automation: 'partial',
    condition: 'Programmatic heading levels logically match the visual heading presentation within the heading structure.' },
  '10.D': { name: '1.3.1-list-type', wcag: '1.3.1', automation: 'partial',
    condition: 'All visually apparent lists are programmatically identified according to their type.' },
  '11.A': { name: '3.1.1-page-language-defined', wcag: '3.1.1', automation: 'auto',
    condition: 'The default human language of each web page can be programmatically determined.' },
  '11.B': { name: '3.1.2-part-language-defined', wcag: '3.1.2', automation: 'partial',
    condition: 'The human language for any content segment that differs from the default human language of the page can be programmatically determined.',
    note: 'Passages in a language other than the page language need a lang attribute. The tool validates existing lang attributes but cannot find unmarked passages.' },
  '12.A': { name: '2.4.2-page-title-defined', wcag: '2.4.2', automation: 'auto',
    condition: 'A <title> element is defined for the web page.' },
  '12.B': { name: '2.4.2-page-title-purpose', wcag: '2.4.2', automation: 'partial',
    condition: 'The <title> element identifies the contents or purpose of the web page.' },
  '12.C': { name: '4.1.2-frame-title', wcag: '4.1.2', automation: 'auto',
    condition: 'Each <frame> has a title attribute that describes its content.' },
  '12.D': { name: '4.1.2-iframe-name', wcag: '4.1.2', automation: 'partial',
    condition: 'The combination of accessible name and description for each <iframe> describes its content.' },
  '13.A': { name: '1.4.1-color-meaning', wcag: '1.4.1', automation: 'partial',
    condition: 'Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.' },
  '13.B': { name: '1.3.3-sensory-info', wcag: '1.3.3', automation: 'partial',
    condition: 'Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components, such as shape, size, visual location, orientation, or sound.' },
  '13.C': { name: '1.4.3-contrast', wcag: '1.4.3', automation: 'auto',
    condition: 'The visual presentation of text and images of text have sufficient contrast.' },
  '14.A': { name: '1.3.1-table-identification', wcag: '1.3.1', automation: 'partial',
    condition: 'Each data table has programmatic markup to identify it as a table.' },
  '14.B': { name: '1.3.1-cell-header-association', wcag: '1.3.1', automation: 'partial',
    condition: 'All data cells are programmatically associated with relevant headers.' },
  '14.C': { name: '1.3.1-layout-table-structure', wcag: '1.3.1', automation: 'auto',
    condition: 'The layout table does not use ARIA role="table" and does not include table header structure and relationship elements and/or associated attributes.' },
  '15.A': { name: '1.3.1-meaningful-content-css-before-after', wcag: '1.3.1', automation: 'partial',
    condition: 'For the meaningful content provided via CSS pseudo-elements ::before and ::after, equivalent information is available in another way.' },
  '15.B': { name: '1.3.2-content-order-meaning-CSS-position', wcag: '1.3.2', automation: 'partial',
    condition: 'The reading order of the content (in context) is correct and the meaning of the content (in context) is preserved without CSS positioning.' },
  '16.A': { name: '1.2.1-audio-transcript-text', wcag: '1.2.1', automation: 'partial',
    condition: 'A text-based alternative is provided for audio-only content that provides an accurate and complete representation of the audio-only content.' },
  '16.B': { name: '1.2.1-video-alternative-equivalent', wcag: '1.2.1', automation: 'partial',
    condition: 'The video-only content information is also available through an equivalent text or audio alternative.' },
  '17.A': { name: '1.2.2-captions-equivalent', wcag: '1.2.2', automation: 'partial',
    condition: 'The multimedia provides accurate captions for the audio content.' },
  '17.B': { name: '1.2.5-audio-description-equivalent', wcag: '1.2.5', automation: 'partial',
    condition: 'The multimedia provides an equivalent soundtrack (combination of narration and audio descriptions) for the video content.' },
  '17.C': { name: '1.2.4-captions-live-equivalent', wcag: '1.2.4', automation: 'manual',
    condition: 'The live multimedia provides accurate captions for the audio content.',
    note: 'Only applies to live streams.' },
  '17.D': { name: '503.4-caption-description-controls', wcag: '508 503.4', automation: 'partial',
    condition: 'The media player provides user controls for closed captions and audio descriptions.' },
  '17.E': { name: '503.4.1-caption-control', wcag: '508 503.4.1', automation: 'manual',
    condition: 'User controls for captions are provided at the same menu level as the user controls for volume or program selection.' },
  '17.F': { name: '503.4.2-description-control', wcag: '508 503.4.2', automation: 'manual',
    condition: 'User controls for audio descriptions are provided at the same menu level as the user controls for volume or program selection.' },
  '18.A': { name: '1.4.4-resize-text', wcag: '1.4.4', automation: 'partial',
    condition: 'There is a mechanism to resize, scale, or zoom in on the text to at least 200% of its original size without loss of content or functionality.' },
  '19.A': { name: '2.4.5-multiple-ways', wcag: '2.4.5', automation: 'partial',
    condition: 'There are two or more ways to locate a web page within a set of web pages.' },
  '20.A': { name: '4.1.1-parsing', wcag: '4.1.1', automation: 'manual',
    condition: 'This test should be recorded as NOT TESTED.',
    note: 'Trusted Tester records 20.A as Not Tested. Duplicate ids that break label or ARIA references are reported under the test they affect.' },
};

export const TEST_IDS = Object.keys(CATALOG);

export function testInfo(id) {
  return CATALOG[id] || { name: 'unknown', wcag: '', automation: 'manual', condition: '' };
}

export const IMPACTS = ['critical', 'serious', 'moderate', 'minor'];
